TimesheetApplication/Models/ClockEvents.cs
namespace TimesheetApplication.Models
{
    public class ClockEvents
    {
        public Guid UserId { get; set; }
        public string Username { get; set; }
        public DateTime Time { get; set; }
        public string EventType { get; set; }
    }
}

TimesheetApplication/Models/ClockIn.cs
namespace TimesheetApplication.Models
{
    public class ClockIn
    {
        public string Username {  get; set; }
    }
}

TimesheetApplication/Models/ClockOut.cs
namespace TimesheetApplication.Models
{
    public class ClockOut
    {
        public string Username { get; set; }

    }
}

TimesheetApplication/Models/CreateUser.cs
using System.ComponentModel.DataAnnotations;

namespace TimesheetApplication.Models
{
    public class CreateUser
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        [Required(ErrorMessage = "First name is required")]
        public string FirstName { get; set; } = string.Empty;
        [Required(ErrorMessage = "Last name is required")]
        public string LastName { get; set; } = string.Empty;
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invaliid email address")]
        public string Email { get; set; } = string.Empty;
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W).{8,}$", ErrorMessage = "at least 8 characters, at least one uppercase, at least one lowercase, at least one digit, at least one special character")]
        public string Password { get; set; } = string.Empty;
        [Required(ErrorMessage = "Username is required")]
        public string UserName { get; set; } = string.Empty;
    }
}

TimesheetApplication/Models/ErrorViewModel.cs
namespace TimesheetApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TimesheetApplication/Models/GetUserEntries.cs
using TimesheetApplication.DB.Entities;

namespace TimesheetApplication.Models
{
    public class GetUserEntries
    {
        public Guid UserId { get; set; }
        public string firstName { get; set; } = string.Empty;
        public string lastName { get; set; } = string.Empty;
        public string UserName { get; set; } = string.Empty;

        public List<TimeEntry> timeEntries { get; set; } = new List<TimeEntry>();


    }
}

TimesheetApplication/Models/UserEntriesRequest.cs
namespace TimesheetApplication.Models
{
    public class UserEntriesRequest
    {
        public string userName {  get; set; }
    }
}

TimesheetApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TimesheetApplication.Models;

namespace TimesheetApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TimesheetApplication/Controllers/TimeEntryController.cs
using Microsoft.AspNetCore.Mvc;
using TimesheetApplication.Repository;
using TimesheetApplication.Services_BusinessLogic;

namespace TimesheetApplication.Controllers
{
    public class TimeEntryController : Controller
    {
        private readonly IClockEventServices _clockEventServices;
        private readonly IUserRepository _userRepository;

        public TimeEntryController(IClockEventServices clockEventServices, IUserRepository userRepository)
        {
            _clockEventServices = clockEventServices;
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
           
            return View();
        }

        [HttpGet]
        public IActionResult ClockIn ()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ClockIn (string userName)
        {
            var user = _userRepository.GetUserByUsername (userName);
            if (user != null)
            {
                var userClockIn = _clockEventServices.ClockIn(user.Id);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult ClockOut()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ClockOut(string userName)
        {
            var user = _userRepository.GetUserByUsername(userName);
            if (user != null)
            {
                var userClockOut = _clockEventServices.ClockOut(user.Id);
                return RedirectToAction("Index");

            }

            return View();
        }

        [HttpGet]

        public IActionResult UserEntriesRequest()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult UserEntriesRequest(string userName)
        {
            var user = _userRepository.GetUserByUsername(userName);
            if (user != null)
            {
                TempData["userName"] = user.UserName;
                return RedirectToAction("GetClockEntries");

            }
            return View();
        }


        [HttpGet]
        public IActionResult GetClockEntries(string userName)
        {
            string UserName = TempData["userName"] as string;
            userName = UserName;
            var userClockEntries = _clockEventServices.userEntries(userName);
            return View(userClockEntries);
        }
    }
}

TimesheetApplication/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TimesheetApplication.Models;
using TimesheetApplication.Services_BusinessLogic;

namespace TimesheetApplication.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserServices _services;

        public UserController(IUserServices services)
        {
            _services = services;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateUser(CreateUser createUser)
        {
            
                CreateUser user = _services.RegisterUser(createUser);
                return View(user);
           
        }
    }
}

TimesheetApplication/Views/Home/Index.cshtml
@* @{
    ViewData["Title"] = "Home Page";
} *@
<link href="@Url.Content("~/css/Home.css")" rel="stylesheet" type="text/css" />

<body>
    <div class="container-main">
        <a class="create-user-btn all-btn" asp-area="" asp-controller="User" asp-action="Index">
            
                Register User
            
        </a>

        <a class="clock-in-btn all-btn" asp-area="" asp-controller="TimeEntry" asp-action="Index">Clock in-Clock out</a>

        <a class="view-entries-btn all-btn" asp-area="" asp-controller="TimeEntry" asp-action="UserEntriesRequest">View Staff clock entries</a>



    </div>
</body>

TimesheetApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimesheetApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TimesheetApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimesheetApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                      @*   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Register User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeEntry" asp-action="Index">Time Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeEntry" asp-action="UserEntriesRequest">Clock Entries</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @* <div class="container"> *@
        <main role="main">
            @RenderBody()
        </main>
    @* </div> *@

    @* <footer class="border-top footer text-muted"> *@
       @*  <div class="container">
            &copy; 2023 - TimesheetApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    @* </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TimesheetApplication/Views/TimeEntry/ClockIn.cshtml
@model TimesheetApplication.Models.ClockIn



@{
    ViewData["Title"] = "ClockIn";
}

<link href="@Url.Content("~/css/home.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/createUser.css")" rel="stylesheet" type="text/css" />


<h1>Clock In</h1>



<div class="row container-main">
    <div class="col-md-4">
        <form asp-action="ClockIn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group mb-2">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" class="all-btn" style="color: white; background-color: green" value="Clock In" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="back-btn mt-3">
    <a asp-action="Index">Back</a>
</div>

TimesheetApplication/Views/TimeEntry/ClockOut.cshtml
@model TimesheetApplication.Models.ClockOut

@{
    ViewData["Title"] = "ClockOut";
}

<link href="@Url.Content("~/css/home.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/createUser.css")" rel="stylesheet" type="text/css" />


<h1>Clock Out</h1>


<div class="row container-main">
    <div class="col-md-4">
        <form asp-action="ClockOut">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" class="all-btn" style="color: white; background-color: green" value="Clock Out" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="back-btn mt-3">
    <a asp-action="Index" >Back</a>
</div>

TimesheetApplication/Views/TimeEntry/GetClockEntries.cshtml
@model TimesheetApplication.Models.GetUserEntries

@{
    ViewData["Title"] = "GetClockEntries";
}



<h1>Staff Clock Entries</h1>


  <div>

        <hr />
        <dl class="row">
       
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.firstName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.firstName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.lastName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.lastName)
            </dd>
          
        </dl>
  </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                   User name
                </th>
                <th>
                    Event Type
                </th>
                <th>
                    Time
                </th>
            
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.timeEntries)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
               
                   
                </tr>
            }
        </tbody>
    </table>
    <div class="back-btn mt-3">
        
        <a asp-action="Index" >Back</a>
    </div>

TimesheetApplication/Views/TimeEntry/Index.cshtml
@using TimesheetApplication.DB.Entities;



<link href="@Url.Content("~/css/Home.css")" rel="stylesheet" type="text/css" />

<link href="@Url.Content("~/css/createUser.css")" rel="stylesheet" type="text/css" />



<h1>Time Entry</h1>

@model User  // Assuming userId is passed

<div class="container-main">

    @using (Html.BeginForm("ClockIn", "TimeEntry", new { userId = Model }, FormMethod.Post) )
    {

        <input type="submit" class="all-btn" style="color: white; background-color: green" value="Clock In" />
        
    }

    @using (Html.BeginForm("ClockOut", "TimeEntry", new { userId = Model }, FormMethod.Post))
    {
        <input type="submit" class="all-btn" style="color: white; background-color: green" value="Clock Out" />
    }
</div>

TimesheetApplication/Views/TimeEntry/UserEntriesRequest.cshtml
@model TimesheetApplication.Models.UserEntriesRequest

@{
    ViewData["Title"] = "UserEntriesRequest";
}

<link href="@Url.Content("~/css/home.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/createUser.css")" rel="stylesheet" type="text/css" />


<h2>Enter Staff Username</h2>



<div class="row container-main">
    <div class="col-md-4">
        <form asp-action="UserEntriesRequest">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="userName" class="control-label" style="color: white"><h3>Username</h3></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Enter" class="all-btn" />
            </div>
        </form>
    </div>
</div>

<div class="back-btn mt-3">
    <a asp-action="Index" style="text-decoration: none; color: white">Back</a>
</div>

TimesheetApplication/Views/User/CreateUser.cshtml
@model TimesheetApplication.Models.CreateUser

@{
    ViewData["Title"] = "CreateUser";
}

<link href="@Url.Content("~/css/createUser.css")" rel="stylesheet" type="text/css" />

<h1>Staff Details</h1>

<div class="container-main" style="background-color:green; color: white">
    <h4>New Staff Created</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10" style="text-decoration: none; color: white">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>
<div class="back-btn"> 
    
    <a asp-action="Index" style="text-decoration: none; color: white ">Back</a>
</div>

TimesheetApplication/Views/User/Index.cshtml
@model TimesheetApplication.Models.CreateUser

@{
    ViewData["Title"] = "Index";
}

<link href="@Url.Content("~/css/createUser.css")" rel="stylesheet" type="text/css"



    <h2 class="m-5">Register Staff</h2>

<div class="row container-main" style="color: white;">
    <div class="col-md-4">
        <form asp-action="CreateUser" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label hidden asp-for="Id" class="control-label"></label>
                <input hidden asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="back-btn mt-2">
    <a asp-action="Index" style="text-decoration: none; color: white ">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}